### ISSUE TITLE
External database password not working as expected

### ISSUE THREAD

**Issue by ngc4579** [infrahq/helm-charts#28]
The configuration for an external database as explained in the [README](https://github.com/infrahq/helm-charts/tree/main/charts/infra-server#readme) does not seem to work:

```yaml
---
config:
  dbHost: postgres.example.com
  dbPort: 5432
  dbName: mydatabase
  dbUsername: myusername
  dbPassword: env:POSTGRES_DB_PASSWORD

server:
  env:
    - name: POSTGRES_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: mypassword
```

Starting the server with an accordingly prepared secret does not work (bad credentials). This does **not** occur when inserting the password into the `values.yaml` directly:

```yaml
config:
  ...
  dbPassword: <somePassword>
```

It seems the server does not evaluate the prefix `env:` in order to use the mentioned environment variable instead of a string literal.
